<a href="https://colab.research.google.com/github/Akanksha-Ceris/100-days-of-machine-learning/blob/main/numpyarraypro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

[1 2 3 4 5]


In [2]:
arr_2d = np.array([[2,3,4,5],[6,7,8,9]])
print(arr_2d)

[[2 3 4 5]
 [6 7 8 9]]


In [3]:
# shape - find the dimension of the array
# shape return a tuple (row,column0 ) for  2 d arrays
print("shape of arr_2d:",arr_2d.shape)

shape of arr_2d: (2, 4)


In [4]:
arr_3d = np.array([[[1,2,3],[4,5,6],[8,9,7]]])
print(arr_3d)

[[[1 2 3]
  [4 5 6]
  [8 9 7]]]


In [5]:
print("shape of 3_arr:",arr_3d.shape)

shape of 3_arr: (1, 3, 3)


In [6]:
# find the array of  data type of array element:
print("data type of arr_1d:",arr_1d.dtype)

data type of arr_1d: int64


In [9]:
float_arr_1d = arr_1d.astype(float)
print("array after converting to integers:",float_arr_1d)

array after converting to integers: [1. 2. 3. 4. 5.]


In [11]:
print("Data type after conversion:",float_arr_1d.dtype)

Data type after conversion: float64


In [12]:
# ndim : it calculate number of dimentsions
# ndim gives how many dimesions (levels) the array has
print("number of dimension in arr_1d:",arr_1d.ndim)

number of dimension in arr_1d: 1


In [13]:
print("number of dimension in arr_2d:",arr_2d.ndim)

number of dimension in arr_2d: 2


In [14]:
print("number of dimesion in arr_3d",arr_3d.ndim)

number of dimesion in arr_3d 3
